#!/bin/sh

set -x

/usr/sbin/rngd
/sbin/ip addr add 10.0.2.15/24 dev eth0
ip addr show
/bin/sleep 20
/sbin/ip route add default via 10.0.2.2
ip addr show

cat /sys/firmware/qemu_fw_cfg/by_name/opt/erl/raw
